#!/usr/bin/env node
// =====================================================
// tools/build-core.js — build the two shared JS bundles
// =====================================================
// The four heavy public pages (index, business, search, browse) each
// loaded the same 9 small files as 9 separate requests. This joins
// them into two bundles, one per loading mode, and stamps the bundle
// tag in each page with a content hash so the 1-year asset cache
// invalidates itself — no more hand-bumping ?v= on these.
//
//   assets/js/dl-core.js        sync   — must run before inline page code
//   assets/js/dl-core-defer.js  defer  — self-initialising UI modules
//
// RULE: after editing ANY source file listed below, run
//         node tools/build-core.js
//       and commit the rebuilt bundles together with the source.
//       `node tools/build-core.js --check` exits 1 if a bundle is stale
//       (use it before pushing).
//
// The source files stay in the repo unchanged: pages that load only
// one or two of them (top, discover, card, panel/*) keep using the
// individual files.
// =====================================================
'use strict';
const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const JS   = path.join(ROOT, 'assets', 'js');

// Order matters inside each bundle: same relative order the pages used.
const BUNDLES = {
  'dl-core.js':       { attr: '',       files: ['dl-config.js', 'supabase-init.js', 'hours.js', 'city-persist.js', 'mobile-nav.js'] },
  'dl-core-defer.js': { attr: ' defer', files: ['error-reporter.js', 'photo-fit.js', 'nav.js', 'pwa.js', 'dl-city-cleanup.js'] },
};
const PAGES = ['index.html', 'business.html', 'search.html', 'browse.html'];

const check = process.argv.includes('--check');
let stale = false;

function sha(s){ return crypto.createHash('sha1').update(s).digest('hex').slice(0, 10); }

function build(name, spec){
  const parts = spec.files.map(f => {
    const src = fs.readFileSync(path.join(JS, f), 'utf8');
    return `\n/* ---- ${f} (${sha(src)}) ---- */\n${src.trim()}\n`;
  });
  // Join with ';' so a file that ends without one cannot chain into the
  // next IIFE as a call:  })()\n(function(){  →  })();(function(){
  const body = '/* GENERATED by tools/build-core.js — do not edit; edit the source files and rebuild. */\n'
             + `/* sources: ${spec.files.join(', ')} */\n`
             + parts.join(';\n') + '\n';
  const hash = sha(body);
  const out  = path.join(JS, name);
  const cur  = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (cur !== body){
    stale = true;
    if (!check){ fs.writeFileSync(out, body); console.log('wrote', name, body.length, 'bytes', hash); }
    else console.log('STALE', name);
  } else console.log('up to date', name, hash);
  return hash;
}

const hashes = {};
for (const [name, spec] of Object.entries(BUNDLES)) hashes[name] = build(name, spec);

// Stamp the tag in each page:  <script src="/assets/js/dl-core.js?v=HASH">
for (const page of PAGES){
  const p = path.join(ROOT, page);
  let html = fs.readFileSync(p, 'utf8');
  let changed = false;
  for (const [name, spec] of Object.entries(BUNDLES)){
    const re = new RegExp(`<script src="/assets/js/${name.replace('.', '\\.')}\\?v=[^"]*"[^>]*></script>`);
    const tag = `<script src="/assets/js/${name}?v=${hashes[name]}"${spec.attr}></script>`;
    if (!re.test(html)){ console.error(`ERROR ${page}: no ${name} tag found`); process.exitCode = 1; continue; }
    const next = html.replace(re, tag);
    if (next !== html){ html = next; changed = true; }
  }
  if (changed){
    stale = true;
    if (!check){ fs.writeFileSync(p, html); console.log('stamped', page); }
    else console.log('STALE tag in', page);
  }
}

if (check && stale){ console.error('\nBundles are stale — run: node tools/build-core.js'); process.exit(1); }
